-- Developer: Ahmet Kaymak
-- Date: 25.01.2017
-- Description: TYPES_OF_DRUGS insert scriptiyle tüm elemanlar eklendi.

INSERT INTO TYPES_OF_DRUGS VALUES('A01','Ağız Sağlığı İlaçları','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A02','Mide İlaçları','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A03','Gastrointestinal Fonksiyonel Hastalıklar','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A04','Bulantı ve Kusmada Kullanılan İlaçlar','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A05','Safra Kesesi ve Karaciğer','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A06','Kabızlık İlaçları','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A07','İshal İlaçları, Barsak Antienflamatuar ve Antienfektifleri','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A08','Obezite Tedavisi','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A09','Sindirimi Kolaylaştıran İlaçlar','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A10','Diyabet (Şeker Hastalığı) İlaçları','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A11','Vitamin İlaçları','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A12','Mineraller','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A14','Anabolik İlaçlar','A');
INSERT INTO TYPES_OF_DRUGS VALUES('A16','Diğer Sindirim Sistemi ve Metabolizma İlaçları','A');
INSERT INTO TYPES_OF_DRUGS VALUES('B01','Antitrombotikler','B');
INSERT INTO TYPES_OF_DRUGS VALUES('B02','Kanama Durdurucu İlaçlar','B');
INSERT INTO TYPES_OF_DRUGS VALUES('B03','Anemi (Kansızlık) İlaçları','B');
INSERT INTO TYPES_OF_DRUGS VALUES('B05','Kan ve Perfüzyon Solüsyonları','B');
INSERT INTO TYPES_OF_DRUGS VALUES('B06','Hematolojik Ajanlar','B');
INSERT INTO TYPES_OF_DRUGS VALUES('C01','Kalp İlaçları','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C02','Antihipertansif İlaçlar (Yüksek Tansiyon İlaçları)','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C03','Diüretik İlaçlar - İdrar Arttırıcı İlaçlar','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C04','Periferik Vazodilatörler','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C05','Vazoprotektifler','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C07','Beta Bloke Edici Ajanlar','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C08','Kalsiyum Kanal Blokerleri','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C09','Kan Basıncını Düzenleyen İlaçlar','C');
INSERT INTO TYPES_OF_DRUGS VALUES('C10','Lipid Metabolizması İlaçları','C');
INSERT INTO TYPES_OF_DRUGS VALUES('D01','Dermatolojik Mantar Tedavisi','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D02','Yumuşatıcı ve Koruyucu İlaçlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D03','Yara Ülser Tedavisi','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D04','Antiprüritik İlaçlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D05','Antipsoriatik İlaçlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D06','Dermatolojik Antibiyotik ve Kemoterapötik İlaçlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D07','Dermatolojik Kortikosteroidler','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D08','Antiseptik ve Dezenfektan İlaçlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D09','İlaçlı Pansumanlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D10','Akne İlaçları','D');
INSERT INTO TYPES_OF_DRUGS VALUES('D11','Diğer Dermatolojik İlaçlar','D');
INSERT INTO TYPES_OF_DRUGS VALUES('G01','Jinekolojik Antiinfektif ve Antiseptikler','G');
INSERT INTO TYPES_OF_DRUGS VALUES('G02','Diğer Jinekolojik İlaçlar','G');
INSERT INTO TYPES_OF_DRUGS VALUES('G03','Cinsiyet Hormonları ve Genital Sistem','G');
INSERT INTO TYPES_OF_DRUGS VALUES('G04','Ürolojik İlaçlar','G');
INSERT INTO TYPES_OF_DRUGS VALUES('H01','Hipofiz ve Hipotalamus Hormonları ve Analogları','H');
INSERT INTO TYPES_OF_DRUGS VALUES('H02','Sistemik Kortikosteroidler','H');
INSERT INTO TYPES_OF_DRUGS VALUES('H03','Tiroid İlaçları','H');
INSERT INTO TYPES_OF_DRUGS VALUES('H04','Pankreas','H');
INSERT INTO TYPES_OF_DRUGS VALUES('H05','Kalsiyum Metabolizması','H');
INSERT INTO TYPES_OF_DRUGS VALUES('J01','Antibakteriyel (Antibiyotik) İlaçlar','J');
INSERT INTO TYPES_OF_DRUGS VALUES('J02','Antimikotik İlaçlar','J');
INSERT INTO TYPES_OF_DRUGS VALUES('J04','Antimikobakteriyel İlaçlar','J');
INSERT INTO TYPES_OF_DRUGS VALUES('J05','Sistemik Antiviral İlaçlar','J');
INSERT INTO TYPES_OF_DRUGS VALUES('J06','İmmün Serum ve İmmünoglobülinler','J');
INSERT INTO TYPES_OF_DRUGS VALUES('J07','Aşılar','J');
INSERT INTO TYPES_OF_DRUGS VALUES('L01','Antineoplastik İlaçlar (Kanser İlaçları) ','L');
INSERT INTO TYPES_OF_DRUGS VALUES('L02','Hormonal Tedavi İlaçları','L');
INSERT INTO TYPES_OF_DRUGS VALUES('L03','İmmünostimülanlar','L');
INSERT INTO TYPES_OF_DRUGS VALUES('L04','İmmünsupresif Ajanlar','L');
INSERT INTO TYPES_OF_DRUGS VALUES('M01','Antienflamatuar ve Antiromatikler','M');
INSERT INTO TYPES_OF_DRUGS VALUES('M02','Vücut Yüzeyine Uygulanan Kas-Eklem Ağrısı İlaçları','M');
INSERT INTO TYPES_OF_DRUGS VALUES('M03','Kas Gevşeticiler','M');
INSERT INTO TYPES_OF_DRUGS VALUES('M04','Gut Hastalığı İlaçları','M');
INSERT INTO TYPES_OF_DRUGS VALUES('M05','Kemik','M');
INSERT INTO TYPES_OF_DRUGS VALUES('M09','Diğer Kas İskelet Sistemi İlaçları','M');
INSERT INTO TYPES_OF_DRUGS VALUES('N01','Anestezi İlaçları','N');
INSERT INTO TYPES_OF_DRUGS VALUES('N02','Ağrı Kesici / Ateş Düşürücüler (Aneljezik)','N');
INSERT INTO TYPES_OF_DRUGS VALUES('N03','Antiepileptik İlaçlar','N');
INSERT INTO TYPES_OF_DRUGS VALUES('N04','Parkinson İlaçları','N');
INSERT INTO TYPES_OF_DRUGS VALUES('N05','Psikoleptikler (Psikolojik İlaçlar)','N');
INSERT INTO TYPES_OF_DRUGS VALUES('N06','Psikoanaleptikler','N');
INSERT INTO TYPES_OF_DRUGS VALUES('N07','Diğer Sinir Sistemi İlaçları','N');
INSERT INTO TYPES_OF_DRUGS VALUES('P01','Antiprotozoal İlaçlar','P');
INSERT INTO TYPES_OF_DRUGS VALUES('P02','Antihelmintik İlaçlar','P');
INSERT INTO TYPES_OF_DRUGS VALUES('P03','Ektoparazit İlaçları','P');
INSERT INTO TYPES_OF_DRUGS VALUES('R01','Burunla İlgili İlaçlar','R');
INSERT INTO TYPES_OF_DRUGS VALUES('R02','Boğaz','R');
INSERT INTO TYPES_OF_DRUGS VALUES('R03','Solunum Sisteminde Tıkanma - Astım İlaçları','R');
INSERT INTO TYPES_OF_DRUGS VALUES('R05','Soğuk Algınlığı ve Öksürük İlaçları','R');
INSERT INTO TYPES_OF_DRUGS VALUES('R06','Sistemik Antihistaminikler','R');
INSERT INTO TYPES_OF_DRUGS VALUES('R07','Diğer Solunum Sistemi İlaçları','R');
INSERT INTO TYPES_OF_DRUGS VALUES('S01','Göze Uygulanan İlaçlar','S');
INSERT INTO TYPES_OF_DRUGS VALUES('S02','Kulak Hastalıkları','S');
INSERT INTO TYPES_OF_DRUGS VALUES('S03','Göz ve Kulak İlaçları','S');
INSERT INTO TYPES_OF_DRUGS VALUES('V01','Allerjenler','V');
INSERT INTO TYPES_OF_DRUGS VALUES('V03','Diğer Tüm Terapötik İlaçlar','V');
INSERT INTO TYPES_OF_DRUGS VALUES('V04','Tanı Ajanları','V');
INSERT INTO TYPES_OF_DRUGS VALUES('V06','Genel Besin İlaçları','V');
INSERT INTO TYPES_OF_DRUGS VALUES('V07','Tedavi Edici Olmayan Diğer Tüm Ürünler','V');
INSERT INTO TYPES_OF_DRUGS VALUES('V08','Kontrast Medya','V');
INSERT INTO TYPES_OF_DRUGS VALUES('V09','Radyofarmasötik İlaçlar','V');
