-- Developer: Ahmet Kaymak
-- Date: 27.01.2017
-- Description: Oluşturulan ilk ilaç veri tabanı için ilaç üreticilerinin insert scriptleri oluşturuldu.

INSERT INTO DRUG_COMPANIES
VALUES('1','ABBOTT');

INSERT INTO DRUG_COMPANIES
VALUES('2','ABBVIE');

INSERT INTO DRUG_COMPANIES
VALUES('3','ABDI IBRAHIM');

INSERT INTO DRUG_COMPANIES
VALUES('4','ABDI IBRAHIM OTSUKA');

INSERT INTO DRUG_COMPANIES
VALUES('5','ABDI IBRAHIM PAZARLAMA');

INSERT INTO DRUG_COMPANIES
VALUES('6','ABDI IBRAHIMOTSUKA');

INSERT INTO DRUG_COMPANIES
VALUES('7','ABFEN FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('8','ACON ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('9','ACTAVIS');

INSERT INTO DRUG_COMPANIES
VALUES('10','ACTELION');

INSERT INTO DRUG_COMPANIES
VALUES('11','ADEKA');

INSERT INTO DRUG_COMPANIES
VALUES('12','ADILNA');

INSERT INTO DRUG_COMPANIES
VALUES('13','AKAR FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('14','AKIN ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('15','AKSU FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('16','AKUR');

INSERT INTO DRUG_COMPANIES
VALUES('17','ALCON');

INSERT INTO DRUG_COMPANIES
VALUES('18','ALI RAIF');

INSERT INTO DRUG_COMPANIES
VALUES('19','ALK');

INSERT INTO DRUG_COMPANIES
VALUES('20','ALLERGAN');

INSERT INTO DRUG_COMPANIES
VALUES('21','AMGEN');

INSERT INTO DRUG_COMPANIES
VALUES('22','ANGELINI ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('23','ARGIS');

INSERT INTO DRUG_COMPANIES
VALUES('24','ARIS');

INSERT INTO DRUG_COMPANIES
VALUES('25','AROMA');

INSERT INTO DRUG_COMPANIES
VALUES('26','ARTIAS MEDIKAL TICARET LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('27','ARVEN');

INSERT INTO DRUG_COMPANIES
VALUES('28','ASET');

INSERT INTO DRUG_COMPANIES
VALUES('29','ASSOS');

INSERT INTO DRUG_COMPANIES
VALUES('30','ASTELLAS');

INSERT INTO DRUG_COMPANIES
VALUES('31','ASTELLAS PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('32','ASTRA MEDIKAL TIBBI ALETLER ITH.IHR. TIC.LTD.STI.');

INSERT INTO DRUG_COMPANIES
VALUES('33','ASTRA ZENECA');

INSERT INTO DRUG_COMPANIES
VALUES('34','ATA ILAC SAGLIK URUNLERI SAN.TIC.LTD.STI.');

INSERT INTO DRUG_COMPANIES
VALUES('35','ATABAY');

INSERT INTO DRUG_COMPANIES
VALUES('36','ATABAY KIMYA');

INSERT INTO DRUG_COMPANIES
VALUES('37','AVICENNA');

INSERT INTO DRUG_COMPANIES
VALUES('38','AVIS');

INSERT INTO DRUG_COMPANIES
VALUES('39','AYMED');

INSERT INTO DRUG_COMPANIES
VALUES('40','AYSET TIBBI URUNLER');

INSERT INTO DRUG_COMPANIES
VALUES('41','AYSET TIBBI URUNLER VE PLASTIK TEKSTIL ELEKTRONIK GIDA TEMIZLIK MADDELERI SAN. A.S');

INSERT INTO DRUG_COMPANIES
VALUES('42','B.BRAUN');

INSERT INTO DRUG_COMPANIES
VALUES('43','B.E.K SAGLIK URUNLERI EGITIM TURIZM EMLAK VE DANISMANLIK HIZMETLERI SAN.VE TIC.LTD.STI.');

INSERT INTO DRUG_COMPANIES
VALUES('44','B.E.K SAGLİK URUNLERI');

INSERT INTO DRUG_COMPANIES
VALUES('45','BASEL');

INSERT INTO DRUG_COMPANIES
VALUES('46','BAUSCH&LOMB');

INSERT INTO DRUG_COMPANIES
VALUES('47','BAUSCH&LOMB ');

INSERT INTO DRUG_COMPANIES
VALUES('48','BAXTER TURKEY RENAL HIZMETLER');

INSERT INTO DRUG_COMPANIES
VALUES('49','BAYER');

INSERT INTO DRUG_COMPANIES
VALUES('50','BAYER ');

INSERT INTO DRUG_COMPANIES
VALUES('51','BAYER TURK KIMYA SAN');

INSERT INTO DRUG_COMPANIES
VALUES('52','BAYERTURK KIMYA');

INSERT INTO DRUG_COMPANIES
VALUES('53','BECTON DICKINSON ITHALAT IHRACAT LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('54','BELGA');

INSERT INTO DRUG_COMPANIES
VALUES('55','BERAT BERAN');

INSERT INTO DRUG_COMPANIES
VALUES('56','BERK ');

INSERT INTO DRUG_COMPANIES
VALUES('57','BERK-FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('58','BERKO');

INSERT INTO DRUG_COMPANIES
VALUES('59','BERKO ');

INSERT INTO DRUG_COMPANIES
VALUES('60','BERKO ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('61','BERKSAM');

INSERT INTO DRUG_COMPANIES
VALUES('62','BIEM');

INSERT INTO DRUG_COMPANIES
VALUES('63','BIEM ');

INSERT INTO DRUG_COMPANIES
VALUES('64','BIKAR');

INSERT INTO DRUG_COMPANIES
VALUES('65','BILIM');

INSERT INTO DRUG_COMPANIES
VALUES('66','BIOCODEX');

INSERT INTO DRUG_COMPANIES
VALUES('67','BIOFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('68','BIOGEN');

INSERT INTO DRUG_COMPANIES
VALUES('69','BIOGEN ');

INSERT INTO DRUG_COMPANIES
VALUES('70','BIOKAN');

INSERT INTO DRUG_COMPANIES
VALUES('71','BIOTA');

INSERT INTO DRUG_COMPANIES
VALUES('72','BIOVESTA');

INSERT INTO DRUG_COMPANIES
VALUES('73','BOEHRINGER INGELHEIM');

INSERT INTO DRUG_COMPANIES
VALUES('74','BRISTOL MYERS SQUIBB');

INSERT INTO DRUG_COMPANIES
VALUES('75','BRISTOL MYERS SQUIBB ');

INSERT INTO DRUG_COMPANIES
VALUES('76','CASEL');

INSERT INTO DRUG_COMPANIES
VALUES('77','CDK SAGLIK URUNLERI TICARET ANONIM SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('78','CDK SAGLIK URUNLERI TICARET ANONIM ŞIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('79','CELGENE');

INSERT INTO DRUG_COMPANIES
VALUES('80','CELLTRION');

INSERT INTO DRUG_COMPANIES
VALUES('81','CELTIS');

INSERT INTO DRUG_COMPANIES
VALUES('82','CELTIS ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('83','CEM FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('84','CENTURION ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('85','CENTURION PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('86','CHIESI');

INSERT INTO DRUG_COMPANIES
VALUES('87','CSL BEHRING');

INSERT INTO DRUG_COMPANIES
VALUES('88','DAIICHI SANKYO');

INSERT INTO DRUG_COMPANIES
VALUES('89','DEFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('90','DEM');

INSERT INTO DRUG_COMPANIES
VALUES('91','DEM ');

INSERT INTO DRUG_COMPANIES
VALUES('92','DEM ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('93','DEM İLAC');

INSERT INTO DRUG_COMPANIES
VALUES('94','DENTORAL MEDIFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('95','DERMAN');

INSERT INTO DRUG_COMPANIES
VALUES('96','DEVA');

INSERT INTO DRUG_COMPANIES
VALUES('97','DEVA HOLDING');

INSERT INTO DRUG_COMPANIES
VALUES('98','DEVAMED ILAC VE KIMYA SANAYI TICARET LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('99','DEVITA ILAC GIDA SAG LIK URN.MED.ITH.IHR. SAN.VE TIC.LTD.ŞTI.');

INSERT INTO DRUG_COMPANIES
VALUES('100','DG FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('101','DINCSA');

INSERT INTO DRUG_COMPANIES
VALUES('102','DIYAB SAGLIK URUNLERI ');

INSERT INTO DRUG_COMPANIES
VALUES('103','DROGSAN');

INSERT INTO DRUG_COMPANIES
VALUES('104','EBV');

INSERT INTO DRUG_COMPANIES
VALUES('105','ECZACIBASI BAXALTA');

INSERT INTO DRUG_COMPANIES
VALUES('106','ECZACIBASI BAXTER');

INSERT INTO DRUG_COMPANIES
VALUES('107','ECZACIBASI ILAC PAZARLAMA');

INSERT INTO DRUG_COMPANIES
VALUES('108','EFFECTUS');

INSERT INTO DRUG_COMPANIES
VALUES('109','EGIS');

INSERT INTO DRUG_COMPANIES
VALUES('110','EGIS ');

INSERT INTO DRUG_COMPANIES
VALUES('111','EIP ECZACIBASI ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('112','EMBIL');

INSERT INTO DRUG_COMPANIES
VALUES('113','EMKAR');

INSERT INTO DRUG_COMPANIES
VALUES('114','ER-KIM');

INSERT INTO DRUG_COMPANIES
VALUES('115','EXELTIS');

INSERT INTO DRUG_COMPANIES
VALUES('116','EXELTIS ILAC SAN. A.Ş.');

INSERT INTO DRUG_COMPANIES
VALUES('117','FARMA-TEK');

INSERT INTO DRUG_COMPANIES
VALUES('118','FARMACORP ILAÇ');

INSERT INTO DRUG_COMPANIES
VALUES('119','FARMAKO');

INSERT INTO DRUG_COMPANIES
VALUES('120','FARMALAS');

INSERT INTO DRUG_COMPANIES
VALUES('121','FARMANOVA');

INSERT INTO DRUG_COMPANIES
VALUES('122','FARMATEK');

INSERT INTO DRUG_COMPANIES
VALUES('123','FARMATEK ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('124','FERRING  ');

INSERT INTO DRUG_COMPANIES
VALUES('125','FERRING ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('126','FRESENIUS KABI');

INSERT INTO DRUG_COMPANIES
VALUES('127','FRESENIUS MEDIKAL');

INSERT INTO DRUG_COMPANIES
VALUES('128','GALEN');

INSERT INTO DRUG_COMPANIES
VALUES('129','GALEPHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('130','GEN');

INSERT INTO DRUG_COMPANIES
VALUES('131','GEN ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('132','GENERICA');

INSERT INTO DRUG_COMPANIES
VALUES('133','GENESIS');

INSERT INTO DRUG_COMPANIES
VALUES('134','GETIZMEN AYSEL YUSUF');

INSERT INTO DRUG_COMPANIES
VALUES('135','GILEAD');

INSERT INTO DRUG_COMPANIES
VALUES('136','GILEAD SCIENCES');

INSERT INTO DRUG_COMPANIES
VALUES('137','GLAXO SMITHKLINE');

INSERT INTO DRUG_COMPANIES
VALUES('138','GLAXO SMITHKLINE TUKETICI SAGLIGI');

INSERT INTO DRUG_COMPANIES
VALUES('139','GLAXOSMITHKLINE');

INSERT INTO DRUG_COMPANIES
VALUES('140','GLAXOSMITHKLINE TUKETICI SAGLIGI');

INSERT INTO DRUG_COMPANIES
VALUES('141','GLOBAL PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('142','GRIPIN');

INSERT INTO DRUG_COMPANIES
VALUES('143','GRIPIN ');

INSERT INTO DRUG_COMPANIES
VALUES('144','GUERBET');

INSERT INTO DRUG_COMPANIES
VALUES('145','GUREL');

INSERT INTO DRUG_COMPANIES
VALUES('146','HAKAY');

INSERT INTO DRUG_COMPANIES
VALUES('147','HAS BIOTECH');

INSERT INTO DRUG_COMPANIES
VALUES('148','HAVER');

INSERT INTO DRUG_COMPANIES
VALUES('149','HAYAT TIBBI ALETLER ');

INSERT INTO DRUG_COMPANIES
VALUES('150','HELBA');

INSERT INTO DRUG_COMPANIES
VALUES('151','HELBA ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('152','HEMAT');

INSERT INTO DRUG_COMPANIES
VALUES('153','HUSNU ARSAN');

INSERT INTO DRUG_COMPANIES
VALUES('154','I.E ULAGAY');

INSERT INTO DRUG_COMPANIES
VALUES('155','IBSA');

INSERT INTO DRUG_COMPANIES
VALUES('156','ILKO');

INSERT INTO DRUG_COMPANIES
VALUES('157','IME DC SAGLIK URUNLERI');

INSERT INTO DRUG_COMPANIES
VALUES('158','IME DC SAGLIK URUNLERI SAN.VE TIC.LTD.STI');

INSERT INTO DRUG_COMPANIES
VALUES('159','INNOGENS');

INSERT INTO DRUG_COMPANIES
VALUES('160','INTENDIS ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('161','INVENTIM');

INSERT INTO DRUG_COMPANIES
VALUES('162','ISIK GRUP ILAC MEDIKAL TIBBI');

INSERT INTO DRUG_COMPANIES
VALUES('163','ISTANBUL ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('164','ITF ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('165','IYON SAGLIK MEDIKAL KOZMETIK ITH.IHR.VE SAN.TIC.LTD.STI.');

INSERT INTO DRUG_COMPANIES
VALUES('166','IYON SAGLIK MEDIKAL KOZMETIK ITHALAT IHRACAT LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('167','JOHNSON AND JOHNSONSIHHI MALZ.SAN.VE TIC.LTD.ŞTI.');

INSERT INTO DRUG_COMPANIES
VALUES('168','JOHNSON&JOHNSON');

INSERT INTO DRUG_COMPANIES
VALUES('169','KANSUK');

INSERT INTO DRUG_COMPANIES
VALUES('170','KARFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('171','KENTFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('172','KEYMEN');

INSERT INTO DRUG_COMPANIES
VALUES('173','KOCAK');

INSERT INTO DRUG_COMPANIES
VALUES('174','KOCAK FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('175','KOCSEL');

INSERT INTO DRUG_COMPANIES
VALUES('176','KOCSEL ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('177','KONSINA ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('178','KOZMED');

INSERT INTO DRUG_COMPANIES
VALUES('179','KURTSAN');

INSERT INTO DRUG_COMPANIES
VALUES('180','LABORATOIRES BAILLEUL');

INSERT INTO DRUG_COMPANIES
VALUES('181','LAFAR');

INSERT INTO DRUG_COMPANIES
VALUES('182','LAURUS');

INSERT INTO DRUG_COMPANIES
VALUES('183','LEO PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('184','LIBA');

INSERT INTO DRUG_COMPANIES
VALUES('185','LILLY');

INSERT INTO DRUG_COMPANIES
VALUES('186','LIVA');

INSERT INTO DRUG_COMPANIES
VALUES('187','LIVA ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('188','LOGUS');

INSERT INTO DRUG_COMPANIES
VALUES('189','LUNDBECK');

INSERT INTO DRUG_COMPANIES
VALUES('190','MALLINCKRODT');

INSERT INTO DRUG_COMPANIES
VALUES('191','MAMMA');

INSERT INTO DRUG_COMPANIES
VALUES('192','MAMSEL');

INSERT INTO DRUG_COMPANIES
VALUES('193','MEDA');

INSERT INTO DRUG_COMPANIES
VALUES('194','MEDA PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('195','MEDISEC TIBBI CIHAZ VE URUNLERI');

INSERT INTO DRUG_COMPANIES
VALUES('196','MEDISEC TIBBI CIHAZ VE URUNLERI ITH.IHR. SANAYI VE TIC. LIM. S.');

INSERT INTO DRUG_COMPANIES
VALUES('197','MEDISEC TIBBI CIHAZ VE URUNLERI ITHALAT IHRACAT SANAYI VE TICARET LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('198','MEDSAN');

INSERT INTO DRUG_COMPANIES
VALUES('199','MEGA FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('200','MELUSIN');

INSERT INTO DRUG_COMPANIES
VALUES('201','MENTA PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('202','MERCK ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('203','MERCK SHARP & DOHME');

INSERT INTO DRUG_COMPANIES
VALUES('204','METIN ECZA');

INSERT INTO DRUG_COMPANIES
VALUES('205','MONEM FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('206','MONTERO');

INSERT INTO DRUG_COMPANIES
VALUES('207','MT SAGLIK URUNLERI SANAYI VE TICARET ANONIM SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('208','MUNIR SAHIN');

INSERT INTO DRUG_COMPANIES
VALUES('209','MUSTAFA NEVZAT');

INSERT INTO DRUG_COMPANIES
VALUES('210','NEP PHARMA SAGLIK URUNLERI SANAYI VE TICARET LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('211','NESTLE');

INSERT INTO DRUG_COMPANIES
VALUES('212','NEUTEC ILAC SAN.');

INSERT INTO DRUG_COMPANIES
VALUES('213','NEUTEC ILAC SAN. ');

INSERT INTO DRUG_COMPANIES
VALUES('214','NEUTEC INHALER');

INSERT INTO DRUG_COMPANIES
VALUES('215','NEUTEC TOPLAM KALITE');

INSERT INTO DRUG_COMPANIES
VALUES('216','NOBEL');

INSERT INTO DRUG_COMPANIES
VALUES('217','NOBEL ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('218','NOBEL ILAC PAZARLAMA');

INSERT INTO DRUG_COMPANIES
VALUES('219','NOBEL ILAC SANAYI');

INSERT INTO DRUG_COMPANIES
VALUES('220','NOBEL SAGLIK');

INSERT INTO DRUG_COMPANIES
VALUES('221','NOVARTIS');

INSERT INTO DRUG_COMPANIES
VALUES('222','NOVARTIS SAGLIK');

INSERT INTO DRUG_COMPANIES
VALUES('223','NOVO NORDISK');

INSERT INTO DRUG_COMPANIES
VALUES('224','NOVONORDISK');

INSERT INTO DRUG_COMPANIES
VALUES('225','NULL');

INSERT INTO DRUG_COMPANIES
VALUES('226','NUMIL');

INSERT INTO DRUG_COMPANIES
VALUES('227','NUTRIMED');

INSERT INTO DRUG_COMPANIES
VALUES('228','NUVOMED');

INSERT INTO DRUG_COMPANIES
VALUES('229','NYCOMED');

INSERT INTO DRUG_COMPANIES
VALUES('230','OMEGA PHARMA ');

INSERT INTO DRUG_COMPANIES
VALUES('231','ONFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('232','ONKO');

INSERT INTO DRUG_COMPANIES
VALUES('233','OPAKIM');

INSERT INTO DRUG_COMPANIES
VALUES('234','ORNA');

INSERT INTO DRUG_COMPANIES
VALUES('235','ORO');

INSERT INTO DRUG_COMPANIES
VALUES('236','ORVA');

INSERT INTO DRUG_COMPANIES
VALUES('237','OSEL');

INSERT INTO DRUG_COMPANIES
VALUES('238','PALMER');

INSERT INTO DRUG_COMPANIES
VALUES('239','PENSA ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('240','PENSA PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('241','PFIZER');

INSERT INTO DRUG_COMPANIES
VALUES('242','PFIZER PFE');

INSERT INTO DRUG_COMPANIES
VALUES('243','PHARMACIA');

INSERT INTO DRUG_COMPANIES
VALUES('244','PHARMACTIVE');

INSERT INTO DRUG_COMPANIES
VALUES('245','PHARMADA');

INSERT INTO DRUG_COMPANIES
VALUES('246','PHARMADA ILAC SAN');

INSERT INTO DRUG_COMPANIES
VALUES('247','PHARMADIA ILAC SANAYI');

INSERT INTO DRUG_COMPANIES
VALUES('248','PHARMALINE');

INSERT INTO DRUG_COMPANIES
VALUES('249','PHARMET');

INSERT INTO DRUG_COMPANIES
VALUES('250','PIERRE FABRE');

INSERT INTO DRUG_COMPANIES
VALUES('251','PLATIN');

INSERT INTO DRUG_COMPANIES
VALUES('252','PLATIN KIMYA');

INSERT INTO DRUG_COMPANIES
VALUES('253','POLIFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('254','POLPHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('255','PROCTER & GAMBLE');

INSERT INTO DRUG_COMPANIES
VALUES('256','PROMEDICA');

INSERT INTO DRUG_COMPANIES
VALUES('257','PUSULA PHARMA ILAC MEDIKAL SAGLIK SANAYI VE TICARET LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('258','PUSULA PHARMA ILAÇ MEDIKAL SAGLIK SANAYI VE TICARET LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('259','QUEISSER FARMA ');

INSERT INTO DRUG_COMPANIES
VALUES('260','RA A.S');

INSERT INTO DRUG_COMPANIES
VALUES('261','RA ILAC ');

INSERT INTO DRUG_COMPANIES
VALUES('262','RASYONEL');

INSERT INTO DRUG_COMPANIES
VALUES('263','RDC');

INSERT INTO DRUG_COMPANIES
VALUES('264','RDC ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('265','RECKITT BENCKISER');

INSERT INTO DRUG_COMPANIES
VALUES('266','RECORDATI');

INSERT INTO DRUG_COMPANIES
VALUES('267','ROCHE');

INSERT INTO DRUG_COMPANIES
VALUES('268','ROCHE ');

INSERT INTO DRUG_COMPANIES
VALUES('269','ROCHE DIAGNOSTICS TURKEY A.S.');

INSERT INTO DRUG_COMPANIES
VALUES('270','ROCHE DIAGNOSTICS TURKEY ANONIM SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('271','RP FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('272','SABA');

INSERT INTO DRUG_COMPANIES
VALUES('273','SANDOZ');

INSERT INTO DRUG_COMPANIES
VALUES('274','SANFRA ILAC VE TIBBI URUNLER ITHALAT VE IHRACAT PAZARLAMA LIMITED SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('275','SANOFI');

INSERT INTO DRUG_COMPANIES
VALUES('276','SANOFI ');

INSERT INTO DRUG_COMPANIES
VALUES('277','SANOFI AVENTIS');

INSERT INTO DRUG_COMPANIES
VALUES('278','SANOFI PASTEUR');

INSERT INTO DRUG_COMPANIES
VALUES('279','SANOFI SAGLIK URUNLERI');

INSERT INTO DRUG_COMPANIES
VALUES('280','SANOVEL');

INSERT INTO DRUG_COMPANIES
VALUES('281','SANTA FARMA');

INSERT INTO DRUG_COMPANIES
VALUES('282','SAY');

INSERT INTO DRUG_COMPANIES
VALUES('283','SCHERING PLOUGH');

INSERT INTO DRUG_COMPANIES
VALUES('284','SELTEK');

INSERT INTO DRUG_COMPANIES
VALUES('285','SEPA TIBBI CIHAZLAR VE KIMYEVI MADD. TIC.LTD.STI.');

INSERT INTO DRUG_COMPANIES
VALUES('286','SERVIER');

INSERT INTO DRUG_COMPANIES
VALUES('287','SET MEDIKAL SANAYI V E TIC.A.S.');

INSERT INTO DRUG_COMPANIES
VALUES('288','SEZA');

INSERT INTO DRUG_COMPANIES
VALUES('289','SHIRE ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('290','SMF ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('291','TAKEDA');

INSERT INTO DRUG_COMPANIES
VALUES('292','TALAYMAN SEYFI SABRI');

INSERT INTO DRUG_COMPANIES
VALUES('293','TALU ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('294','TAYMED');

INSERT INTO DRUG_COMPANIES
VALUES('295','TEKA TEKNIK');

INSERT INTO DRUG_COMPANIES
VALUES('296','TEOFARMA');

INSERT INTO DRUG_COMPANIES
VALUES('297','TERRA');

INSERT INTO DRUG_COMPANIES
VALUES('298','TEVA ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('299','THEA PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('300','TOPRAK');

INSERT INTO DRUG_COMPANIES
VALUES('301','TOPRAK ');

INSERT INTO DRUG_COMPANIES
VALUES('302','TRIMPEKS');

INSERT INTO DRUG_COMPANIES
VALUES('303','TRIMPEKS ITHALAT IHRACAT ');

INSERT INTO DRUG_COMPANIES
VALUES('304','TRIMPEKS ITHALAT IHRACAT TURIZM VE TICARET ANONIM SIRKETI');

INSERT INTO DRUG_COMPANIES
VALUES('305','TRIOZER');

INSERT INTO DRUG_COMPANIES
VALUES('306','TRIPHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('307','TUM EKIP');

INSERT INTO DRUG_COMPANIES
VALUES('308','TURKTIPSAN');

INSERT INTO DRUG_COMPANIES
VALUES('309','UCB PHARMA');

INSERT INTO DRUG_COMPANIES
VALUES('310','UFSA');

INSERT INTO DRUG_COMPANIES
VALUES('311','ULAGAYLAR');

INSERT INTO DRUG_COMPANIES
VALUES('312','ULKAR');

INSERT INTO DRUG_COMPANIES
VALUES('313','ULKAR ILAC PAZARLAMA');

INSERT INTO DRUG_COMPANIES
VALUES('314','UMUT ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('315','VEFA ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('316','VEM ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('317','VITALIS');

INSERT INTO DRUG_COMPANIES
VALUES('318','VLD');

INSERT INTO DRUG_COMPANIES
VALUES('319','VLD DANISMANLIK');

INSERT INTO DRUG_COMPANIES
VALUES('320','WORLD MEDICINE');

INSERT INTO DRUG_COMPANIES
VALUES('321','YAVUZ ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('322','YENI ILAC');

INSERT INTO DRUG_COMPANIES
VALUES('323','YENI RECORDATI');

INSERT INTO DRUG_COMPANIES
VALUES('324','YENI SARK');

INSERT INTO DRUG_COMPANIES
VALUES('325','YENISEHIR');

INSERT INTO DRUG_COMPANIES
VALUES('326','ZENTIVA');

INSERT INTO DRUG_COMPANIES
VALUES('327','ZINDE-LAB SAGLIK HIZ LTD.STI.');