-- Developer: Ahmet Kaymak
-- Date: 27.01.2017
-- Description: Oluşturulan ilk ilaç veri tabanı için ilaç üreticilerinin insert scriptleri oluşturuldu.

INSERT INTO DRUG_COMPANIES
VALUES('1','ABBOTT',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('2','ABBVIE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('3','ABDI IBRAHIM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('4','ABDI IBRAHIM OTSUKA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('5','ABDI IBRAHIM PAZARLAMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('6','ABDI IBRAHIMOTSUKA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('7','ABFEN FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('8','ACON ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('9','ACTAVIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('10','ACTELION',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('11','ADEKA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('12','ADILNA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('13','AKAR FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('14','AKIN ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('15','AKSU FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('16','AKUR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('17','ALCON',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('18','ALI RAIF',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('19','ALK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('20','ALLERGAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('21','AMGEN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('22','ANGELINI ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('23','ARGIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('24','ARIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('25','AROMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('26','ARTIAS MEDIKAL TICARET LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('27','ARVEN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('28','ASET',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('29','ASSOS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('30','ASTELLAS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('31','ASTELLAS PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('32','ASTRA MEDIKAL TIBBI ALETLER ITH.IHR. TIC.LTD.STI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('33','ASTRA ZENECA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('34','ATA ILAC SAGLIK URUNLERI SAN.TIC.LTD.STI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('35','ATABAY',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('36','ATABAY KIMYA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('37','AVICENNA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('38','AVIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('39','AYMED',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('40','AYSET TIBBI URUNLER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('41','AYSET TIBBI URUNLER VE PLASTIK TEKSTIL ELEKTRONIK GIDA TEMIZLIK MADDELERI SAN. A.S',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('42','B.BRAUN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('43','B.E.K SAGLIK URUNLERI EGITIM TURIZM EMLAK VE DANISMANLIK HIZMETLERI SAN.VE TIC.LTD.STI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('44','B.E.K SAGLÝK URUNLERI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('45','BASEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('46','BAUSCH&LOMB',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('47','BAUSCH&LOMB ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('48','BAXTER TURKEY RENAL HIZMETLER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('49','BAYER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('50','BAYER ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('51','BAYER TURK KIMYA SAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('52','BAYERTURK KIMYA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('53','BECTON DICKINSON ITHALAT IHRACAT LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('54','BELGA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('55','BERAT BERAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('56','BERK ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('57','BERK-FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('58','BERKO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('59','BERKO ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('60','BERKO ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('61','BERKSAM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('62','BIEM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('63','BIEM ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('64','BIKAR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('65','BILIM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('66','BIOCODEX',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('67','BIOFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('68','BIOGEN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('69','BIOGEN ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('70','BIOKAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('71','BIOTA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('72','BIOVESTA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('73','BOEHRINGER INGELHEIM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('74','BRISTOL MYERS SQUIBB',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('75','BRISTOL MYERS SQUIBB ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('76','CASEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('77','CDK SAGLIK URUNLERI TICARET ANONIM SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('78','CDK SAGLIK URUNLERI TICARET ANONIM ÞIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('79','CELGENE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('80','CELLTRION',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('81','CELTIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('82','CELTIS ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('83','CEM FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('84','CENTURION ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('85','CENTURION PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('86','CHIESI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('87','CSL BEHRING',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('88','DAIICHI SANKYO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('89','DEFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('90','DEM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('91','DEM ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('92','DEM ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('93','DEM ÝLAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('94','DENTORAL MEDIFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('95','DERMAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('96','DEVA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('97','DEVA HOLDING',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('98','DEVAMED ILAC VE KIMYA SANAYI TICARET LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('99','DEVITA ILAC GIDA SAG LIK URN.MED.ITH.IHR. SAN.VE TIC.LTD.ÞTI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('100','DG FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('101','DINCSA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('102','DIYAB SAGLIK URUNLERI ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('103','DROGSAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('104','EBV',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('105','ECZACIBASI BAXALTA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('106','ECZACIBASI BAXTER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('107','ECZACIBASI ILAC PAZARLAMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('108','EFFECTUS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('109','EGIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('110','EGIS ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('111','EIP ECZACIBASI ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('112','EMBIL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('113','EMKAR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('114','ER-KIM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('115','EXELTIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('116','EXELTIS ILAC SAN. A.Þ.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('117','FARMA-TEK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('118','FARMACORP ILAÇ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('119','FARMAKO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('120','FARMALAS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('121','FARMANOVA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('122','FARMATEK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('123','FARMATEK ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('124','FERRING  ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('125','FERRING ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('126','FRESENIUS KABI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('127','FRESENIUS MEDIKAL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('128','GALEN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('129','GALEPHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('130','GEN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('131','GEN ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('132','GENERICA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('133','GENESIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('134','GETIZMEN AYSEL YUSUF',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('135','GILEAD',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('136','GILEAD SCIENCES',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('137','GLAXO SMITHKLINE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('138','GLAXO SMITHKLINE TUKETICI SAGLIGI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('139','GLAXOSMITHKLINE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('140','GLAXOSMITHKLINE TUKETICI SAGLIGI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('141','GLOBAL PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('142','GRIPIN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('143','GRIPIN ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('144','GUERBET',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('145','GUREL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('146','HAKAY',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('147','HAS BIOTECH',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('148','HAVER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('149','HAYAT TIBBI ALETLER ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('150','HELBA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('151','HELBA ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('152','HEMAT',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('153','HUSNU ARSAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('154','I.E ULAGAY',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('155','IBSA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('156','ILKO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('157','IME DC SAGLIK URUNLERI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('158','IME DC SAGLIK URUNLERI SAN.VE TIC.LTD.STI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('159','INNOGENS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('160','INTENDIS ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('161','INVENTIM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('162','ISIK GRUP ILAC MEDIKAL TIBBI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('163','ISTANBUL ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('164','ITF ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('165','IYON SAGLIK MEDIKAL KOZMETIK ITH.IHR.VE SAN.TIC.LTD.STI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('166','IYON SAGLIK MEDIKAL KOZMETIK ITHALAT IHRACAT LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('167','JOHNSON AND JOHNSONSIHHI MALZ.SAN.VE TIC.LTD.ÞTI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('168','JOHNSON&JOHNSON',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('169','KANSUK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('170','KARFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('171','KENTFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('172','KEYMEN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('173','KOCAK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('174','KOCAK FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('175','KOCSEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('176','KOCSEL ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('177','KONSINA ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('178','KOZMED',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('179','KURTSAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('180','LABORATOIRES BAILLEUL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('181','LAFAR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('182','LAURUS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('183','LEO PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('184','LIBA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('185','LILLY',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('186','LIVA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('187','LIVA ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('188','LOGUS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('189','LUNDBECK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('190','MALLINCKRODT',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('191','MAMMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('192','MAMSEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('193','MEDA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('194','MEDA PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('195','MEDISEC TIBBI CIHAZ VE URUNLERI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('196','MEDISEC TIBBI CIHAZ VE URUNLERI ITH.IHR. SANAYI VE TIC. LIM. S.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('197','MEDISEC TIBBI CIHAZ VE URUNLERI ITHALAT IHRACAT SANAYI VE TICARET LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('198','MEDSAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('199','MEGA FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('200','MELUSIN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('201','MENTA PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('202','MERCK ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('203','MERCK SHARP & DOHME',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('204','METIN ECZA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('205','MONEM FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('206','MONTERO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('207','MT SAGLIK URUNLERI SANAYI VE TICARET ANONIM SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('208','MUNIR SAHIN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('209','MUSTAFA NEVZAT',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('210','NEP PHARMA SAGLIK URUNLERI SANAYI VE TICARET LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('211','NESTLE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('212','NEUTEC ILAC SAN.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('213','NEUTEC ILAC SAN. ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('214','NEUTEC INHALER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('215','NEUTEC TOPLAM KALITE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('216','NOBEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('217','NOBEL ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('218','NOBEL ILAC PAZARLAMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('219','NOBEL ILAC SANAYI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('220','NOBEL SAGLIK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('221','NOVARTIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('222','NOVARTIS SAGLIK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('223','NOVO NORDISK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('224','NOVONORDISK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('225','NULL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('226','NUMIL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('227','NUTRIMED',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('228','NUVOMED',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('229','NYCOMED',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('230','OMEGA PHARMA ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('231','ONFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('232','ONKO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('233','OPAKIM',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('234','ORNA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('235','ORO',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('236','ORVA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('237','OSEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('238','PALMER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('239','PENSA ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('240','PENSA PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('241','PFIZER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('242','PFIZER PFE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('243','PHARMACIA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('244','PHARMACTIVE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('245','PHARMADA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('246','PHARMADA ILAC SAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('247','PHARMADIA ILAC SANAYI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('248','PHARMALINE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('249','PHARMET',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('250','PIERRE FABRE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('251','PLATIN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('252','PLATIN KIMYA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('253','POLIFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('254','POLPHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('255','PROCTER & GAMBLE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('256','PROMEDICA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('257','PUSULA PHARMA ILAC MEDIKAL SAGLIK SANAYI VE TICARET LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('258','PUSULA PHARMA ILAÇ MEDIKAL SAGLIK SANAYI VE TICARET LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('259','QUEISSER FARMA ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('260','RA A.S',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('261','RA ILAC ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('262','RASYONEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('263','RDC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('264','RDC ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('265','RECKITT BENCKISER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('266','RECORDATI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('267','ROCHE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('268','ROCHE ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('269','ROCHE DIAGNOSTICS TURKEY A.S.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('270','ROCHE DIAGNOSTICS TURKEY ANONIM SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('271','RP FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('272','SABA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('273','SANDOZ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('274','SANFRA ILAC VE TIBBI URUNLER ITHALAT VE IHRACAT PAZARLAMA LIMITED SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('275','SANOFI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('276','SANOFI ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('277','SANOFI AVENTIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('278','SANOFI PASTEUR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('279','SANOFI SAGLIK URUNLERI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('280','SANOVEL',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('281','SANTA FARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('282','SAY',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('283','SCHERING PLOUGH',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('284','SELTEK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('285','SEPA TIBBI CIHAZLAR VE KIMYEVI MADD. TIC.LTD.STI.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('286','SERVIER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('287','SET MEDIKAL SANAYI V E TIC.A.S.',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('288','SEZA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('289','SHIRE ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('290','SMF ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('291','TAKEDA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('292','TALAYMAN SEYFI SABRI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('293','TALU ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('294','TAYMED',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('295','TEKA TEKNIK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('296','TEOFARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('297','TERRA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('298','TEVA ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('299','THEA PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('300','TOPRAK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('301','TOPRAK ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('302','TRIMPEKS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('303','TRIMPEKS ITHALAT IHRACAT ',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('304','TRIMPEKS ITHALAT IHRACAT TURIZM VE TICARET ANONIM SIRKETI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('305','TRIOZER',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('306','TRIPHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('307','TUM EKIP',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('308','TURKTIPSAN',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('309','UCB PHARMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('310','UFSA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('311','ULAGAYLAR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('312','ULKAR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('313','ULKAR ILAC PAZARLAMA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('314','UMUT ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('315','VEFA ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('316','VEM ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('317','VITALIS',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('318','VLD',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('319','VLD DANISMANLIK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('320','WORLD MEDICINE',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('321','YAVUZ ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('322','YENI ILAC',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('323','YENI RECORDATI',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('324','YENI SARK',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('325','YENISEHIR',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('326','ZENTIVA',now(),now());

INSERT INTO DRUG_COMPANIES
VALUES('327','ZINDE-LAB SAGLIK HIZ LTD.STI.',now(),now());